WIP.

diff --git a/bin/n7 b/bin/n7
--- a/bin/n7
+++ b/bin/n7
@@ -3,7 +3,6 @@
 # N7 - Ad Hoc Task Automation and Orchestration in Bash.
 #
 # TODO:
-#   - Warn about no hosts specified
 #   - 
 
 set -eE
@@ -15,11 +14,12 @@ declare -i N7_VERBOSE=${N7_LOG_LEVELS[INFO]}
 N7::log() {
     local level=${2:-"INFO"}; 
     local -i ilevel=${N7_LOG_LEVELS[$level]?:"Invalid log level: $level"}
-    if [ "$ilevel" -ge "$N7_VERBOSE" ]; then
-        printf "%(%Y-%m-%dT%T%z)T|N7|$USER|$level|$1\n" -1
+    if [[ $ilevel -ge $N7_VERBOSE ]]; then
+        printf "%(%Y-%m-%dT%T%z)T|N7|%s|$level|%s\n" -1 "$USER" "$1"
     fi
 }
 N7::die() { N7::log "$1" ${2:-ERROR} >&2; exit 1; }
+N7::debug() { N7::log "$1" DEBUG >&2; }
 
 N7::print_stack_trace() {
     echo
@@ -27,10 +27,25 @@ N7::print_stack_trace() {
     local i=0; while caller $((i++)); do :; done
     echo
     echo "Failed command: -->$BASH_COMMANDS<--"
-}
+} >&2
 
-N7::is_num() { [ "$1" ] && printf "%.0f" "$1" >/dev/null 2>&1; }
-N7::is_int() { [ "$1" ] && printf "%d" "$1" >/dev/null 2>&1; }
+N7::is_num() { [[ $1 ]] && printf "%.0f" "$1" >/dev/null 2>&1; }
+N7::is_int() { [[ $1 ]] && printf "%d" "$1" >/dev/null 2>&1; }
+
+
+# A shared data stack, meant for passing small amount of data between function calls only.
+#
+# To push on to the stack:                DS+=("item1" "item2" ...)
+# To pop the last item off the stack:     ${DS[-1]}; ds::pop
+# To pop the last $N items off the stack: ${DS[@]:${#DS[@]}-N:N}; ds::pop $N
+#
+DS=()
+ds::pop() {
+    local len=${1:-1}
+    while ((len--)); do
+        unset DS["${#DS[@]} - 1"]
+    done
+}
 
 trap "set +x; N7::print_stack_trace" ERR
 
@@ -91,7 +106,7 @@ while getopts ':hs:m:v:oDkp:-' option; do
         D) N7_CLI_TASK_NO_REDIRECTION=1 ;;
         k) N7_KEEP_RUN_DIR=1 ;;
         p) declare -r N7_SSH_COUNT=$OPTARG 
-           [ "$N7_SSH_COUNT" -gt 0 ] ||
+           [[ $N7_SSH_COUNT -gt 0 ]] ||
                N7::die "Invalid value($N7_SSH_COUNT) for the -p option!"
             ;;
         h) N7::usage; exit ;;
@@ -139,10 +154,10 @@ for host in $N7_HOSTS; do
         fi
         host=${host%:$port}
     fi
-    if [ "${N7_HOST_PORTS[$host]}" ]; then
+    if [[ ${N7_HOST_PORTS["$host"]} ]]; then
         N7::die "Duplicate host entry($host) found in remote host list!"
     fi
-    N7_HOST_PORTS[$host]=:$port
+    N7_HOST_PORTS["$host"]=:$port
 done
 unset host port
 
@@ -151,20 +166,20 @@ declare -r N7_HOSTS
 # N7_HOSTS now contains only hostnames. Port needs to be looked up in
 # N7_HOST_PORTS.
 
-if [ "$N7_SCRIPT" ]; then
+[[ $N7_HOSTS ]] || { N7::log "Empty host list!" WARNING; exit 0; }
+
+if [[ $N7_SCRIPT ]]; then
     N7_SCRIPT_ARGS=("$@")
 fi
 
 # If command line commands are provided then wrap the commands
 # in N7 tasks.
-if [ ! "$N7_SCRIPT" ]; then
+if [[ ! $N7_SCRIPT ]]; then
     i=0
     for cmd in "$@"; do
         eval ".N7::cli_task::$i() {
             : REMOTE=1
-            if [ ! "$N7_CLI_TASK_NO_REDIRECTION" ]; then
-                exec 2>&1
-            fi
+          " $(if [[ ! $N7_CLI_TASK_NO_REDIRECTION ]]; then echo "exec 2>&1"; fi) "
             $cmd
         }"
         let ++i
@@ -280,7 +295,6 @@ N7_SSH_OPTS=${N7_SSH_OPTS:-"
   -o ControlPath=$N7_DIR/tmp/n7-ssh-%h-%p-%r
 "}
 N7_SSH_CMD="ssh $(printf "%s " $N7_SSH_OPTS)"
-N7_SSH_PIDs=$N7_RUN_DIR/.ssh.pids
 N7_SSH_PPIDs=()
 N7_SSH_PIPE_FDs=()  # file descriptors redirected to write to the SSH read pipes.
                     # these FDs exist mainly to keep the pipes open.
@@ -289,10 +303,14 @@ N7_SSH_PIPE_FDs=()  # file descriptors redirected to write to the SSH read pipes
 N7_ANSIBLE_OUT=$N7_REMOTE_RUN_DIR/ansible.out
 declare -r N7_ANSIBLE_OUT
 
+# whether N7::cleanup has been called or not.
+N7_CLEANING_UP=
 
-
+# The shell to switch to once ssh to a remote host. Only Bash is supported.
+N7_REMOTE_SHELL=/bin/bash
 #
 mkdir -p "$N7_DIR" "$N7_DIR/tmp" "$N7_RUNS_DIR" "$N7_RUN_DIR"
+touch $N7_INTERNAL_ERR_FILE
 #---------------------------------------------------------------
 
 
@@ -305,17 +323,17 @@ N7::close_ssh_pipes() {
         eval "exec $fd>&-"
     done
 
-    # kill ssh processes
-    [ -r "$N7_SSH_PIDs" ] && {
-        kill $(<"$N7_SSH_PIDs") >/dev/null 2>&1
-        rm "$N7_SSH_PIDs"
-    }
-
-    # kill -9 each of the whole process groups that's reading the ssh pipes.
-    for pid_pgid in $(ps x -opid,pgid | awk 'NR==1 {next}; {printf("%d,%d\n", $1, $2)}'); do
-        if [[ " ${N7_SSH_PPIDs[*]} " =~ " ${pid_pgid%,*} " ]]; then
-            kill -9 -- -${pid_pgid#*,} >/dev/null 2>&1
-        fi
+    # Kill each of the whole process groups that's reading the ssh pipes.
+    # Do it first with SIGTERM and then finally with SIGKILL.
+    #
+    local sig pids=$(ps x -opid,pgid | awk 'NR==1 {next}; {printf("%d,%d\n", $1, $2)}')
+#    for sig in TERM KILL; do
+    for sig in TERM; do
+        for pid_pgid in $pids; do
+            if [[ " ${N7_SSH_PPIDs[*]} " =~ " ${pid_pgid%,*} " ]]; then
+                kill -$sig -- -${pid_pgid#*,} >/dev/null 2>&1 || true
+            fi
+        done
     done
 
     for host in $N7_HOSTS; do
@@ -325,20 +343,30 @@ N7::close_ssh_pipes() {
 
 
 N7::cleanup() {
-    local last_rc=$?; set +e +E
+    local last_rc=$?
+
+    # To prevent from being called more than once.(eg, from ERR and EXIT)
+    if ! mv "$N7_INTERNAL_ERR_FILE" \
+          "$N7_INTERNAL_ERR_FILE.done" >/dev/null 2>&1; then
+        return
+    fi
+
+    if [[ $last_rc -ne 0 ]]; then
+        set +x; N7::print_stack_trace
+    fi
+
+    set +e +E
 
     # this is to silence bash from reporting to stderr that a
     # child process was killed with SIGKILL.
-    exec 2>>"$N7_INTERNAL_ERR_FILE"
+    exec 2>>"$N7_INTERNAL_ERR_FILE.done"
     
     N7::close_ssh_pipes
     rm -f "$N7_EHOSTS_FILE"
-    if [ ! "$N7_KEEP_RUN_DIR" ]; then
+    if [[ ! $N7_KEEP_RUN_DIR ]]; then
         rm -rf "$N7_RUN_DIR"
     fi
-    if [ "$last_rc" -ne 0 ]; then
-        set +x; N7::print_stack_trace
-    fi
+    exit $last_rc
 }
 
 N7::ssh_read_pipe() { echo "$N7_RUN_DIR/$1.pipe_r"; }
@@ -361,7 +389,7 @@ N7::send_eot_line() {
 }
 
 N7::ssh_ehosts() {
-    if [ -r "$N7_EHOSTS_FILE" ]; then
+    if [[ -r $N7_EHOSTS_FILE ]]; then
         N7_EHOSTS=$(<"$N7_EHOSTS_FILE") 2>/dev/null
         rm -f "$N7_EHOSTS_FILE"
     fi
@@ -369,6 +397,17 @@ N7::ssh_ehosts() {
 }
 
 
+# Output a list of function names matching a specific pattern in the order
+# they are defined in $N7_SCRIPT.
+#
+N7::_get_func_names() {
+    local f line p
+    for f in $(declare -f | grep -- "$1" | cut -d' ' -f1); do
+        line=$(declare -F $f)
+        p=${line#* }; p=${p#* }
+        if [[ $p = $N7_SCRIPT ]]; then printf "%s\n" "$line"; fi
+    done | sort -nk2 | cut -d' ' -f1
+}
 
 
 # N7::load_tasks
@@ -399,22 +438,10 @@ N7::load_tasks() {
     #        show_task_outputs().
 
     shopt -s extdebug
-    N7_TASKS+=($(
-        for f in $(declare -f | grep '^\.' | cut -d' ' -f1); do
-            line=$(declare -F $f)
-            p=${line#* }; p=${p#* }
-            if [ "$p" = "$N7_SCRIPT" ]; then printf "%s\n" "$line"; fi
-        done | sort -nk2 | cut -d' ' -f1)
-    )
-    N7_HANDLERS+=($(
-        for f in $(declare -f | grep '^:' | cut -d' ' -f1); do
-            line=$(declare -F $f)
-            p=${line#* }; p=${p#* }
-            if [ "$p" = "$N7_SCRIPT" ]; then printf "%s\n" "$line"; fi
-        done | sort -nk2 | cut -d' ' -f1)
-    )
+    N7_TASKS+=($(N7::_get_func_names '^\.'))
+    N7_HANDLERS+=($(N7::_get_func_names '^:'))
     shopt -u extdebug
-    if [ ${#N7_TASKS[*]} -le ${#N7_BUILTIN_TASKS[*]} ]; then
+    if [[ ${#N7_TASKS[*]} -le ${#N7_BUILTIN_TASKS[*]} ]]; then
         N7::log "No tasks are defined!" WARNING
     fi
 
@@ -471,39 +498,43 @@ N7::get_task_opt() {
 #
 N7::load_task_opts() {
     local task_idx=-1 task task_opts name val
-    while [[ $# > 0 ]]; do
+    while (( $# > 0 )); do
         name=N7_TASK_OPTS_$((++task_idx))
         task=$1; shift
         task_opts=$(N7::parse_task_opts "$task")
 
-        #HACK: if there's a syntax error with the array assignment then this will exit 1.
-        set -e; source <(echo "declare -gA $name; $name=$task_opts"); set +e
+        declare -gA "$name=$task_opts"
 
-        # check if each option name is valid
+        # check if each option name is valid by removing all known option
+        # names from an array of user specified option names.
         val=($(eval echo '${!'$name'[*]}'))
-        for name in ${N7_TASK_OPT_NAMES[*]}; do val=(${val[*]/#$name}); done
-        if [ "$(echo ${val[*]})" ]; then   #FIXME: option value might conflict with echo's options
+        for name in ${N7_TASK_OPT_NAMES[*]}; do # 
+            val=(${val[*]/#$name})
+        done
+
+        # if there's still any options left over then it's an unknown option.
+        if [[ $(printf %s "${val[*]}") ]]; then
             N7::die "Invalid task options(${val[*]}) in task #$task_idx"
         fi
         
         # validate the TIMEOUT value
         val=$(N7::get_task_opt $task_idx TIMEOUT)
-        [ ! "$val" ] || [ "$val" -gt 0 ] || N7::die "Invalid timeout(\`$val') for task #$task_idx!"
+        [[ ! $val || $val -gt 0 ]] || N7::die "Invalid timeout(\`$val') for task #$task_idx!"
 
         # set NAME to function name if it's not specified.
-        if [ ! "$(eval echo \${N7_TASK_OPTS_$task_idx[NAME]})" ]; then
-            eval N7_TASK_OPTS_$task_idx[NAME]=$task
+        if [[ ! $(eval echo \${N7_TASK_OPTS_$task_idx[NAME]}) ]]; then
+            declare -g "N7_TASK_OPTS_$task_idx[NAME]=$task"
         fi
 
         # deal with LOCAL and REMOTE
         local localremote=$(echo "$task_opts" | grep -P '^\[LOCAL|REMOTE\]=' | tail -n1)
         val=N7_TASK_OPTS_$task_idx
         if [[ ! $localremote ]]; then
-            eval $val[$N7_DEFAULT_TASK_TYPE]=1
+            declare -g "$val[$N7_DEFAULT_TASK_TYPE]=1"
         elif [[ $localremote  == \[LOCAL\]=* ]]; then
-            eval unset $val[REMOTE]
+            unset $val[REMOTE]
         elif [[ $localremote  == \[REMOTE\]=* ]]; then
-            eval unset $val[LOCAL]
+            unset $val[LOCAL]
         fi
     done
 }
@@ -523,21 +554,27 @@ N7::wait_for_task_on_hosts() {
     local task_idx=$1; shift
     local timeout=$(N7::get_task_opt $task_idx TIMEOUT)
     local out_files=$(for h in $*; do N7::ssh_out_file $h; done)
+    # NOTE: $out_files is a newline separated string of pathes.
+    #       The use of IFS=$'\n' below is to make word-splitting split on
+    #       newlines instead of white spaces, because a path may contain spaces.
+
     local eot_lines
 
     timeout=${timeout:-$N7_TASK_TIMEOUT}
     SECONDS=0
     while (( SECONDS < timeout )); do
         sleep 0.01
-        eot_lines=$(IFS=$'\n'; tail -v -n1 $out_files | grep -aPB1 "^$N7_EOT [^ ]+ \b$task_idx\b \d+")
-        # Note: with tail's '==> path <==' headers.
+        eot_lines=$(IFS=$'\n' 
+            tail -v -n1 $out_files |  # with tail's '==> path <==' headers
+            grep -aPB1 "^$N7_EOT [^ ]+ \b$task_idx\b \d+" || true
+        )
 
+        if [[ $eot_lines ]]; then grep "^$N7_EOT" <<<"$eot_lines"; fi
         out_files=$(
             diff <(echo "$eot_lines" | grep "^==>" | cut -d' ' -f2 | sort) \
                  <(echo "$out_files" | sort) | grep '^>' | cut -d' ' -f2
         )
-        [ "$eot_lines" ] && grep "^$N7_EOT" <<<"$eot_lines"
-        [ ! "$out_files" ] && return # ie, all out files have the EOT at the end.
+        if [[ ! $out_files ]]; then return; fi  # ie, all out files have the EOT at the end.
 
     done
     local path oIFS=$IFS
@@ -555,20 +592,21 @@ N7::wait_for_task_on_hosts() {
 #
 N7::wait_for_task() {
     local task_idx=$1; shift
+    local ignore_status=$(N7::get_task_opt $task_idx IGNORE_STATUS)
     local hosts=$*
     local host rc
 
     # wait for the EOT marker at the end in each host's out file
-    while read _ host _ rc _; do
+    while read -r _ host _ rc _; do
 
-        if [ "$rc" != 0 ]; then
+        if [[ $rc != 0 ]]; then
 
             # remove timed out host so that it won't block the next task
-            if [ "$rc" = $N7_ERRNO_TIMEOUT ]; then
+            if [[ $rc = $N7_ERRNO_TIMEOUT ]]; then
                 hosts=$(echo ${hosts/$host})
 
             # remove failed host if the task has no IGNORE_STATUS set
-            elif [ ! "$(N7::get_task_opt $task_idx IGNORE_STATUS)" ]; then
+            elif [[ ! $ignore_status ]]; then
                 hosts=$(echo ${hosts/$host})
             fi
         fi
@@ -591,9 +629,10 @@ N7::ssh_connect() {
     local host port ssh_pipe ssh_out ssh_err fd
     for host in $*; do
         ssh_pipe=$(N7::ssh_read_pipe $host)
-        if [ -e "$ssh_pipe" ]; then
+        if [[ -e $ssh_pipe ]]; then
             continue
         fi
+        N7::debug "Creating pipes for $host..."
         ssh_out=$(N7::ssh_out_file $host) && touch "$ssh_out" && chmod 0600 "$ssh_out"
         ssh_err=$(N7::ssh_err_file $host) && touch "$ssh_err" && chmod 0600 "$ssh_err"
 
@@ -601,26 +640,27 @@ N7::ssh_connect() {
 
         port=${N7_HOST_PORTS[$host]#:}
 
+        N7::debug "Connecting to $host..."
+        N7::debug "$N7_SSH_CMD ${port:+-p$port} $host"
+
         set -m  # temporarily enable job control to create the following
         (       # subshell in its own process group.
-          $N7_SSH_CMD ${port:+-p$port} $host 'exec -l /bin/bash' <"$ssh_pipe" >"$ssh_out" 2>"$ssh_err" &
-          ssh_pid=$!
-          echo $ssh_pid >>"$N7_SSH_PIDs"
-          wait $ssh_pid
-          if [ $? -gt 0 -a $? -lt 128 ]; then
+          $N7_SSH_CMD ${port:+-p$port} $host "exec -l $N7_REMOTE_SHELL" <"$ssh_pipe" >"$ssh_out" 2>"$ssh_err"
+          if [[ $? -gt 0 && $? -lt 128 ]]; then
               N7::log "$(echo "SSH connection to $host disconnected!"; cat "$ssh_err")"
           fi
-
-          # remove the ssh pid from the ssh pid file
-          sed -i '' -e "/^$ssh_pid\$/d" "$N7_SSH_PIDs" >/dev/null 2>&1
 
           # make any further writes to the pipe fail without blocking,
           # then read from the pipe to unblock the process that had written
           # to it before the chmod.
           chmod a-w "$ssh_pipe" &&
-          while true; do cat "$ssh_pipe" >/dev/null; done #FIXME: don't discard the data read?
-        ) 2>>"$N7_INTERNAL_ERR_FILE" & set +m
+          while true; do cat "$ssh_pipe" >/dev/null; done || true #FIXME: don't discard the data read?
+
+        ) 2>>"$N7_INTERNAL_ERR_FILE" &
+        set +m
         N7_SSH_PPIDs+=($!)
+
+        N7::debug "SSH ppid=${N7_SSH_PPIDs[-1]} for $host"
 
         # this is just to keep the pipe from being closed when its
         # write end closes.
@@ -655,7 +695,7 @@ N7::show_task_outputs() {
     for host in $*; do
         out_file=$(N7::ssh_out_file $host)
 
-        if [ "$show_output" ]; then
+        if [[ $show_output ]]; then
             from_line=$(grep -an "^$N7_EOT $host $last_task_idx " "$out_file" |
                     tail -n1 | cut -d: -f1)
             let ++from_line
@@ -704,7 +744,7 @@ N7::run_tasks() {
 
     local host task rc no_subshell sudo
 
-    while [[ $# > 0 && $N7_EHOSTS ]]; do
+    while [[ $# -gt 0 && $N7_EHOSTS ]]; do
         task=$1; shift
         N7_TASK_IDX=${N7_TASK_NAME_2_INDEX[$task]}
 
@@ -713,13 +753,13 @@ N7::run_tasks() {
         N7::log "Running Task: $(N7::get_task_opt $N7_TASK_IDX NAME) ..."
 
         # handle local task, which has no timeout control.
-        if [ "$(N7::get_task_opt $N7_TASK_IDX LOCAL)" ]; then
+        if [[ $(N7::get_task_opt $N7_TASK_IDX LOCAL) ]]; then
             export N7_HOST=localhost;
 
-            if [ "$no_subshell" ]; then $task; else ($task); fi; rc=$?
+            if [[ $no_subshell ]]; then $task; else ($task); fi; rc=$?
             N7::log "localhost rc=$rc"
 
-            if [ "$rc" != 0 -a ! "$(N7::get_task_opt $N7_TASK_IDX IGNORE_STATUS)" ]; then
+            if [[ $rc != 0 && ! $(N7::get_task_opt $N7_TASK_IDX IGNORE_STATUS) ]]; then
                 N7::die "Error running local task #$N7_TASK_IDX: $(N7::get_task_opt $N7_TASK_IDX NAME)"
             fi
 
@@ -740,9 +780,9 @@ N7::run_tasks() {
                            N7_EHOSTS=\$(echo $N7_EHOSTS) \
                            N7_HOST=$(N7::q "$host") \
                     " $host
-                [ "$no_subshell" ] || N7::send_cmd '('             $host
+                [[ $no_subshell ]] || N7::send_cmd '('             $host
                                       N7::send_cmd $task           $host
-                [ "$no_subshell" ] || N7::send_cmd ') </dev/null'  $host
+                [[ $no_subshell ]] || N7::send_cmd ') </dev/null'  $host
                 N7::send_eot_line $host
             done
             N7_EHOSTS=$(N7::wait_for_task $N7_TASK_IDX $N7_EHOSTS)
@@ -782,26 +822,23 @@ N7::run_pre_task_function() {
 #
 N7::run_tasks_on_hosts() {
     local tasks=$1 hosts=$2
-    if [ "$N7_SSH_COUNT" ]; then
+    if [[ $N7_SSH_COUNT ]]; then
         while read hosts; do
             N7::run_tasks "$tasks" "${hosts}"
-            if [ "$(N7::ssh_ehosts)" != "$hosts" ]; then
+            if [[ $(N7::ssh_ehosts) != $hosts ]]; then
                 return $?
             fi
         done < <(tr ' ' '\n' <<<$hosts | paste -d' ' $(seq -f - ${N7_SSH_COUNT}))
     else
         N7::run_tasks "$tasks" "$hosts"
-        if [ "$(N7::ssh_ehosts)" = "$hosts" ]; then
-            return 0
-        else
-            return 1
-        fi
+        [[ $(N7::ssh_ehosts) = $hosts ]]
     fi
 }
 
 
 #
 trap 'N7::cleanup' ABRT ERR TERM QUIT INT EXIT HUP
+# NOTE: N7::cleanup also calls N7::print_stack_trace on ERR.
 #---------------------------------------------------------------
 
 
@@ -846,7 +883,7 @@ trap 'N7::cleanup' ABRT ERR TERM QUIT INT EXIT HUP
 N7::q() { printf "%q\n" "$*"; }
 N7::qm() {
     local result=$(printf "%q " "$@")
-    printf "${result% }\n"
+    printf "%s\n" "${result% }"
 }
 N7::get_sudo() {
     local sudo=${1:-$N7_SUDO}
@@ -1388,9 +1425,22 @@ eval "$(declare -f N7::local::tasks::get_stdout \
 #
 #----------------------------------------------------------------
 
+#--- Load shorthands for builtin functions ----------------------
+#
+n7_ansmod=N7::local::ansible::run_mod
+
+n7_cp=N7::local::files::cp
+_n7_cp_tpl() { $n7_cp "$@" tplcmd=N7::local::files::bash_tpl; }
+n7_cp_tpl=_n7_cp_tpl
+
+n7_remote=N7::local::commands::remote
+n7_remote_output=N7::local::tasks::get_stdout
+n7_file=N7::remote::files::file
+#
+#----------------------------------------------------------------
 
 # Load user's .n7 script
-if [ "$N7_SCRIPT" ]; then
+if [[ $N7_SCRIPT ]]; then
     source "$N7_SCRIPT" "${N7_SCRIPT_ARGS[@]}" || N7::die "Failed loading $N7_SCRIPT!"
 fi
 
