More fixes and some behaviour changes..., a work in progress.

diff --git a/bin/n7 b/bin/n7
--- a/bin/n7
+++ b/bin/n7
@@ -5,7 +5,6 @@
 # TODO:
 #   - allow a task to touch a file to indicate something has changed.
 #   - ansible module integration
-#   - write tests, run tests using docker
 #   - show also stderr for tasks with non-zero exit status
 #   - add example .n7 scripts
 #   - show colorized output
@@ -15,7 +14,7 @@
 
 set -e
 
-declare -A N7_LOG_LEVELS=([DEBUG]=-1 [INFO]=0 [WARNING]=1 [ERROR]=2 [FATAL]=3 [QUIET]=99)
+declare -rA N7_LOG_LEVELS=([DEBUG]=-1 [INFO]=0 [WARNING]=1 [ERROR]=2 [FATAL]=3 [QUIET]=99)
 declare -i N7_VERBOSE=${N7_LOG_LEVELS[INFO]}
 
 N7::log() {
@@ -29,10 +28,12 @@ N7::die() { N7::log "$1" ${2:-ERROR} >&2; exit 1; }
 
 N7::usage() {
   echo "$(echo "\
-    Usage: $(basename "$0") [options] [cmd1 cmd2 ...]
+    Usage: $(basename "$0") [options] [arg1 arg2 ...]
 
-    Each command, if provided, will be run as a N7 task with default task options.
-
+    Each argument, if provided, will be wrapped and run in a N7 *remote* task.
+    However, If the -s option is provided then each argument will be passed to
+    the N7 script as command line arguments.
+        
     Options:
       -h          Show this help. 
 
@@ -41,6 +42,10 @@ N7::usage() {
 
       -s FILE     Source and execute tasks in FILE after running the commands
                   specified on the command line.
+
+      --          Mark the end of command-line options. The rest of command line
+                  arguments won't be parsed as options to n7. This might be
+                  useful for passing options specific to a n7 script.
 
       -v LEVEL    Set the verbose level. Defaults to INFO.
                   Levels available: $(
@@ -58,12 +63,11 @@ N7::usage() {
                   stdout and stderr files from each remote host, etc.
 
       -p COUNT    Limit the number of parallel SSH processes to COUNT at a time.
-                   
 
 " | sed -e 's/    //')"
 }
 
-while getopts ':hs:m:v:okp:' option; do
+while getopts ':hs:m:v:okp:-' option; do
     case $option in
         s) N7_SCRIPT=$OPTARG ;;
         m) N7_HOSTS=$(tr , ' ' <<<"$OPTARG") ;;
@@ -75,12 +79,17 @@ while getopts ':hs:m:v:okp:' option; do
                N7::die "Invalid value($N7_SSH_COUNT) for the -p option!"
             ;;
         h) N7::usage; exit ;;
+        -) break ;;
         :) N7::die "Missing option argument for -$OPTARG" ;;
         \?) N7::die "Unknown option: -$OPTARG" ;;
     esac
 done
 unset option
 shift $(($OPTIND - 1))
+
+if [ "$N7_SCRIPT" ]; then
+    N7_SCRIPT_ARGS=("$@")
+fi
 
 # Read from stdin a list of hostnames, one per line, to ssh into.
 if [ ! "$N7_HOSTS" ]; then N7_HOSTS=$(</dev/stdin); fi
@@ -95,22 +104,27 @@ declare -r N7_HOSTS
 declare -r N7_SCRIPT
 
 # Function name prefix for command-line tasks.
-N7_CLI_TASK_PREFIX=.N7::cli_task::
+declare -r N7_CLI_TASK_PREFIX=.N7::cli_task::
 
 # If command line commands are provided then wrap the commands
 # in N7 tasks.
-i=0
-for cmd in "$@"; do
-    eval "${N7_CLI_TASK_PREFIX}$i() { : REMOTE=1
-        $cmd
-    }"
-    let ++i
-done
-unset cmd i
+if [ ! "$N7_SCRIPT" ]; then
+    i=0
+    for cmd in "$@"; do
+        eval "${N7_CLI_TASK_PREFIX}$i() { : REMOTE=1
+            $cmd
+        }"
+        let ++i
+    done
+    unset cmd i
+fi
 
 # Task names in execution order.
 N7_TASKS=()
+
+# These are N7 built-in tasks used to bootstrap N7.
 N7_BUILTIN_TASKS=(.N7::init_local .N7::init_remote .N7::define_builtins)
+declare -r N7_BUILTIN_TASKS
 
 # In case no LOCAL nor REMOTE task option is set for a task, this will
 # be the default.
@@ -128,31 +142,35 @@ N7_TASK_OPT_NAMES=(
   LOCAL           # set it to run the task locally.
   REMOTE          # set it to run the task remotely.
 
-  #Note: If both LOCAL and REMOTE are set then the task type will be unknown.
-  #      If neither LOCAL nor REMOTE is set then, the task is of the
-  #      $N7_DEFAULT_TASK_TYPE, which defaults to LOCAL.
+  #Note: If both LOCAL and REMOTE are set then the which ever is set
+  #      later overrides the former; if neither LOCAL nor REMOTE is set
+  #      then, the task is of the $N7_DEFAULT_TASK_TYPE, which defaults to
+  #      LOCAL.
 
   IGNORE_STATUS   # set it to run the remaining tasks even if the task exited
                   # with a non-zero exit status. 
 )
 declare -r N7_TASK_OPT_NAMES
 
-N7_TASK_TIMEOUT=${N7_TASK_TIMEOUT:-60}  # default task timeout, in seconds.
+N7_TASK_TIMEOUT=${N7_TASK_TIMEOUT:-60}    # default task timeout, in seconds.
 N7_ERRNO_TIMEOUT=999  # a task exits with this exit code if it's timed out.
 declare -r N7_ERRNO_TIMEOUT
 #Note: this is a special "exit code" since it's > 255 it won't be confused
-#      the task's exit code.
+#      with the task's exit code.
 
 N7_EOT=$(openssl rand -hex 16) # "End Of Task" marker
-declare -r N7_EOT
 #
 # At the end of each a task execution, N7 outputs an EOT line of this form:
 #
-#   "$N7_EOT $host $N7_TASK_IDX $?"
+#   "$N7_EOT $host $N7_TASK_IDX $? changed"
 #
 # where $host is the hostname N7 used to ssh into the host, $N7_TASK_IDX is
-# integral index of the task into the N7_TASKS array, and $? is, of course,
-# the exit status of the last command run by the task.
+# integral index of the task into the N7_TASKS array, and $? is  the exit
+# status of the last command run by the task. 'changed' indicates whether
+# the task has changed the state of the system, and if not, then it's should
+# be a single '-' character instead of 'changed'. Within a task, an user
+# can call the 'N7::remote::tasks::touch_changed' function to mark the task
+# as changed the system state.
 #
 
 N7_NL=$'\n'
@@ -182,7 +200,6 @@ N7_INTERNAL_ERR_FILE=$N7_RUN_DIR/.cleanup.err
 # It can also be overriden by the `sudo` option of the built-in functions
 # that support it. In your own task you can just run sudo by yourself.
 N7_SUDO=${N7_SUDO:-sudo}
-declare -r N7_SUDO
 
 # Where N7 store temporary file on a remote host.
 N7_REMOTE_TMP_DIR=/var/tmp/n7
@@ -200,6 +217,7 @@ N7_SSH_PIDs=$N7_RUN_DIR/.ssh.pids
 N7_SSH_PPIDs=()
 N7_SSH_PIPE_FDs=()  # file descriptors redirected to write to the SSH read pipes.
                     # these FDs exist mainly to keep the pipes open.
+
 
 N7::close_ssh_pipes() {
     local fd pid_pgid host
@@ -311,7 +329,8 @@ N7::load_tasks() {
 #
 # Output the right hand side of an associative array assignment of this form:
 #
-#     '([name1]=value1
+#     '(
+#      [name1]=value1
 #      [name2]=value2
 #        ...
 #      )'
@@ -368,13 +387,14 @@ N7::load_task_opts() {
         fi
 
         # deal with LOCAL and REMOTE
+        local localremote=$(echo "$task_opts" | grep -P '^\[LOCAL|REMOTE\]=' | tail -n1)
         val=N7_TASK_OPTS_$task_idx
-        if [ "$(eval echo \${$val[REMOTE]})" ]; then
-            eval unset $val[LOCAL]
-        elif [ "$(eval echo \${$val[LOCAL]})" ]; then
-            eval unset $val[REMOTE]
-        else
+        if [[ ! $localremote ]]; then
             eval $val[$N7_DEFAULT_TASK_TYPE]=1
+        elif [[ $localremote  == \[LOCAL\]=* ]]; then
+            eval unset $val[REMOTE]
+        elif [[ $localremote  == \[REMOTE\]=* ]]; then
+            eval unset $val[LOCAL]
         fi
     done
 }
@@ -453,6 +473,10 @@ N7::wait_for_task() {
 
 
 # N7::ssh_connect [host1 host2 ...]
+#
+# Establish ssh connections to remote hosts and setup named pipes and
+# I/O redirects for N7 to communicate with the ssh processes and to
+# recieve task outputs.
 #
 N7::ssh_connect() {
     local host ssh_pipe ssh_out ssh_err fd
@@ -682,9 +706,10 @@ N7::local::commands::send_funcs() {
 # N7::local::commands::send_env [name1=value1 name2=value2 ...]
 #
 # Define environment variables on all remote hosts.
+# Space and special shell characters will need to be quoted.
 #
 # Return 0 if all functions are defined successfully on the remote hosts;
-# return 1 if otherwise.
+# return 1 otherwise.
 #
 # This function can only be used from a local task.
 #
@@ -869,7 +894,7 @@ eval "$(declare -f N7::local::tasks::get_stdout \
 
 #-------------
 
-#---N7 Default Intializing Tasks -----------
+#---N7 Initialization Tasks -----------
 
 # This is the very first task that gets run by N7 to bootstrap remote
 # tasks, and environment variables.
@@ -898,7 +923,9 @@ eval "$(declare -f N7::local::tasks::get_stdout \
     mkdir -p "$N7_REMOTE_RUN_DIR" "$N7_REMOTE_TMP_DIR"
 }
 
-.N7::define_builtins() { : REMOTE=1
+.N7::define_builtins() {
+    : REMOTE=1
+    : NO_SUBSHELL=1
 
     N7::q() { printf "%q\n" "$*"; }
     N7::qm() {
@@ -985,11 +1012,21 @@ N7::run_tasks_on_hosts() {
 
 # Load user's .n7 script
 if [ "$N7_SCRIPT" ]; then
-    source "$N7_SCRIPT" || N7::die "Failed loading $N7_SCRIPT!"
+    source "$N7_SCRIPT" "${N7_SCRIPT_ARGS[@]}" || N7::die "Failed loading $N7_SCRIPT!"
 fi
+
+# We've given the .n7 script the chance to mess with some of the globals,
+# now make them read-only.
+declare -r \
+    N7_EOT \
+    N7_SUDO \
+    N7_TASK_TIMEOUT \
+    N7_DEFAULT_TASK_TYPE \
+    N7_SSH_OPTS \
+    N7_SSH_CMD 
+
 N7::load_tasks
 N7::load_task_opts ${N7_TASKS[*]}
-
 
 # Run N7 built-in tasks first
 N7::run_tasks_on_hosts "${N7_BUILTIN_TASKS[*]}" "${N7_HOSTS[*]}" >>"$N7_INTERNAL_ERR_FILE" 2>&1
@@ -1014,6 +1051,7 @@ N7::scope_do() {
         N7::send_eot_line $host -1 0
     done
 }; N7::scope_do; unset -f N7::scope_do
+declare -r N7_TASKS
 
 # Run user's N7 tasks
 N7::log "Run id=$N7_RUN_ID -- N7_DIR=$(N7::q "$N7_DIR") N7_EOT=$N7_EOT"
