rewrite. WIP.

diff --git a/bin/n7 b/bin/n7
--- a/bin/n7
+++ b/bin/n7
@@ -3,7 +3,9 @@
 # N7 - Ad Hoc Task Automation and Orchestration in Bash.
 #
 # TODO:
-#   - for a remote task, we should show stderr when the task fails!
+#   - make set -e and error reporting the default for remote tasks
+#   - make dumping stack trace the default for local tasks
+#   - clean up remote n7 tmp dirs
 #
 
 set -eE
@@ -22,6 +24,9 @@ N7::log() {
 N7::die() { N7::log "$1" ${2:-ERROR} >&2; exit 1; }
 N7::debug() { N7::log "$1" DEBUG >&2; }
 
+# NOTE: this can also be used in a (sub-shelled) local task like this:
+#       trap 'N7::print_stack_trace' ERR
+#
 N7::print_stack_trace() {
     echo
     echo "Stack trace: --------"
@@ -141,6 +146,10 @@ N7_PROG_NAME=$0
 N7_CLI_ARGS=("$@")
 N7_IS_LOCAL=1
 N7_PROG_LINE_COUNT=$(wc -l <"$0")
+
+exec {N7_STDOUT}>&1; export N7_STDOUT
+exec {N7_STDERR}>&2; export N7_STDERR
+
 
 # De-duplicate the hostnames
 N7_HOSTS=$(echo $(echo $N7_HOSTS | tr ' ' '\n' | sort -u | grep -v -- ^-\$))
@@ -279,6 +288,7 @@ N7_SUDO=${N7_SUDO:-sudo}
 # Where N7 store temporary file on a remote host.
 N7_REMOTE_TMP_DIR=/var/tmp/n7
 N7_REMOTE_RUN_DIR=$N7_REMOTE_TMP_DIR/$N7_RUN_ID
+N7_REMOTE_TASKS_SRC=$N7_REMOTE_RUN_DIR/n7_tasks.sh
 
 N7_SSH_OPTS=${N7_SSH_OPTS:-"
   -o BatchMode=yes
@@ -307,57 +317,58 @@ touch $N7_INTERNAL_ERR_FILE
 
 #--- Define the core functions that make up n7 -----------------
 
-N7::close_ssh_pipes() {
-    local fd pid_pgid host
-    for fd in ${N7_SSH_PIPE_FDs[*]}; do
-        eval "exec $fd>&-"
-    done
-
-    # Kill each of the whole process groups that's reading the ssh pipes.
-    # Do it first with SIGTERM and then finally with SIGKILL.
-    #
-    local sig pids=$(ps x -opid,pgid | awk 'NR==1 {next}; {printf("%d,%d\n", $1, $2)}')
-#    for sig in TERM KILL; do
-    for sig in TERM; do
-        for pid_pgid in $pids; do
-            if [[ " ${N7_SSH_PPIDs[*]} " =~ " ${pid_pgid%,*} " ]]; then
-                kill -$sig -- -${pid_pgid#*,} >/dev/null 2>&1 || true
-            fi
-        done
-#        sleep 0.5
-    done
-
-    for host in $N7_HOSTS; do
-        rm -f "$(N7::ssh_read_pipe $host)"
-    done
-}
-
 
 N7::cleanup() {
     local last_rc=$?
 
-    # To prevent from being called more than once.(eg, from ERR and EXIT)
-    if ! mv "$N7_INTERNAL_ERR_FILE" \
-          "$N7_INTERNAL_ERR_FILE.done" >/dev/null 2>&1; then
-        return
-    fi
+    # Restore STDOUT and STDERR
+    exec 1>&$N7_STDOUT 2>&$N7_STDERR
 
+    # Dump stack trace if cleaning up because of an error
     if [[ $last_rc -ne 0 ]]; then
         set +x; N7::print_stack_trace
-        cat "$N7_INTERNAL_ERR_FILE.done" >&2
     fi
 
     set +e +E
 
-    # this is to silence bash from reporting to stderr that a
-    # child process was killed with SIGKILL.
-    exec 2>>"$N7_INTERNAL_ERR_FILE.done"
-    
-    N7::close_ssh_pipes
+    # Close FDs that's keeping the ssh pipes open
+    local fd 
+    for fd in ${N7_SSH_PIPE_FDs[*]}; do
+        eval "exec $fd>&-"
+    done
+
+    # Remove the ssh pipes
+    local host
+    for host in $N7_HOSTS; do
+        rm -f "$(N7::ssh_read_pipe $host)"
+    done
+
     rm -f "$N7_EHOSTS_FILE"
+
+    # Show errors if any
+    if [[ -s $N7_INTERNAL_ERR_FILE ]]; then
+        N7::log "Errors found during initialization or cleanup: --------
+$(<"$N7_INTERNAL_ERR_FILE")" ERROR
+    fi
+
+    # Remove the n7 run dir if not keeping it
     if [[ ! $N7_KEEP_RUN_DIR ]]; then
         rm -rf "$N7_RUN_DIR"
     fi
+
+
+    # This is to keep bash from reporting to stderr that each of the child
+    # process that invokes ssh has been killed.
+    exec 2>/dev/null
+
+    # Kill each of the whole process groups that's reading the ssh pipes.
+    local pid_pgid pids=$(ps x -opid,pgid | awk 'NR==1 {next}; {printf("%d,%d\n", $1, $2)}')
+    for pid_pgid in $pids; do
+        if [[ " ${N7_SSH_PPIDs[*]} " =~ " ${pid_pgid%,*} " ]]; then
+            kill -TERM -- -${pid_pgid#*,}
+        fi
+    done
+
     exit $last_rc
 }
 
@@ -655,21 +666,20 @@ N7::ssh_connect() {
         N7::debug "$N7_SSH_CMD ${port:+-p$port} $host"
 
         set -m  # temporarily enable job control to create the following
-        (       # subshell in its own process group.
-          $N7_SSH_CMD ${port:+-p$port} $host "exec -l $N7_REMOTE_SHELL" <"$ssh_pipe" >"$ssh_out" 2>"$ssh_err"
-          if [[ $? -gt 0 && $? -lt 128 ]]; then
-              N7::log "$(echo "SSH connection to $host disconnected!"; cat "$ssh_err")"
-          fi
+        (       # subshell in its own process group for easy killing during clean up.
+          set +e +E
 
-          # make any further writes to the pipe fail without blocking,
-          # then read from the pipe to unblock the process that had written
-          # to it before the chmod.
-          chmod a-w "$ssh_pipe" &&
+          # Run ssh command and connect its stdin to $ssh_pipe and outputs to files on the file system.
+          $N7_SSH_CMD ${port:+-p$port} $host "exec -l $N7_REMOTE_SHELL" <"$ssh_pipe" >"$ssh_out" 2>"$ssh_err"
+
+          # Make any further writes to the pipe fail without blocking.
+          chmod a-w "$ssh_pipe"
 
           # Inject a time-out EOT line directly into the host outfile to avoid timeout
-          echo $N7_EOT $host -1 $N7_ERRNO_TIMEOUT - > "$(N7::ssh_out_file $host)" &&
+          echo $N7_EOT $host -1 $N7_ERRNO_TIMEOUT - > "$(N7::ssh_out_file $host)"
 
-          while true; do cat "$ssh_pipe" >/dev/null; done || true #FIXME: don't discard the data read?
+          # Read from the pipe to unblock the process that had written to it before the chmod.
+          cat "$ssh_pipe" >/dev/null || true
 
         ) 2>>"$N7_INTERNAL_ERR_FILE" &
         set +m
@@ -755,6 +765,9 @@ N7::run_tasks() {
 
     set -- $1
 
+    local n7_builtin_tasks_count=$(
+        declare -F | cut -d' ' -f3 | grep -P '^\.N7::' | grep -v '::cli_task::' | wc -l)
+
     N7::ssh_connect $N7_EHOSTS
 
     local host task rc no_subshell sudo hosts
@@ -771,13 +784,9 @@ N7::run_tasks() {
         if [[ $(N7::get_task_opt $N7_TASK_IDX LOCAL) ]]; then
             export N7_HOST=localhost;
 
-            local unset_e='' unset_E=''
-            if [[ $- =~ e ]]; then set +e; unset_e=1; fi
-            if [[ $- =~ E ]]; then set +E; unset_E=1; fi
             if [[ $no_subshell ]]; then $task; else ($task); fi; rc=$?
-            if [[ $unset_e ]]; then set -e; fi
-            if [[ $unset_E ]]; then set -E; fi
             N7::log "localhost rc=$rc"
+            #FIXME: this doesn't tell us about the change status of the local task
 
             if [[ $rc != 0 && ! $(N7::get_task_opt $N7_TASK_IDX IGNORE_STATUS) ]]; then
                 N7::die "Error running local task #$N7_TASK_IDX: $(N7::get_task_opt $N7_TASK_IDX NAME)"
@@ -804,7 +813,13 @@ N7::run_tasks() {
                 N7::send_eot_line $host
             done
             N7::wait_for_task $N7_TASK_IDX $hosts
-            N7::show_task_outputs $N7_TASK_IDX $hosts
+
+            # Show output if it's not a built-in tasks, whose outputs are redirected
+            # to $N7_INTERNAL_ERR_FILE
+            #
+            if [[ $N7_TASK_IDX -ge $n7_builtin_tasks_count ]]; then
+                N7::show_task_outputs $N7_TASK_IDX $hosts
+            fi
         fi
 
     done
@@ -853,8 +868,7 @@ N7::run_tasks_on_hosts() {
 
 
 #
-trap 'N7::cleanup' ABRT ERR TERM QUIT INT EXIT HUP
-# NOTE: N7::cleanup also calls N7::print_stack_trace on ERR.
+trap - ERR; trap 'N7::cleanup' EXIT
 #---------------------------------------------------------------
 
 
@@ -868,7 +882,8 @@ trap 'N7::cleanup' ABRT ERR TERM QUIT INT EXIT HUP
 # This is the very first task that gets run by N7 to bootstrap remote
 # tasks, and environment variables.
 #
-.N7::init_remote() { : LOCAL=1; set -e
+.N7::init_remote() {
+    : LOCAL=1
     exec >>"$N7_INTERNAL_ERR_FILE" 2>&1
 
     N7::local::commands::send_env  \
@@ -882,27 +897,32 @@ trap 'N7::cleanup' ABRT ERR TERM QUIT INT EXIT HUP
         'mkdir -p "$N7_REMOTE_RUN_DIR" "$N7_REMOTE_TMP_DIR"'
 
     # define remote tasks on remote hosts
-    local task i=0
-
+    local i task tasks=()
     for task in ${N7_TASKS[*]} ${N7_HANDLERS[*]}; do
-        if [[ $(N7::get_task_opt $i REMOTE) ]]; then
-            N7::local::commands::send_funcs $task
+        i=${N7_TASK_NAME_2_INDEX[$task]}
+        if [[ $(N7::get_task_opt "$i" REMOTE) ]]; then
+            tasks+=($task)
         fi
-        i=$((++i))
     done
+    N7::local::commands::send_funcs ${tasks[*]}
     # NOTE: implementation-wise, handlers are treated just like a task.
 }
 
 .N7::define_remote_builtins() {
     : REMOTE=1
     : NO_SUBSHELL=1
-    if [[ ! $N7_IS_LOCAL ]]; then
-        exec 3>&1 4>&2
-        exec >>"$N7_REMOTE_RUN_DIR/$FUNCNAME" 2>&1
-    fi
 
 # NOTE: Due to NO_SUBSHELL=1, we can't set -e here because then any error
 #       would exit the shell and terminates the ssh session!
+
+    local fd1 fd2
+    exec {fd1}>&1 {fd2}>&2
+
+    if [[ ! $N7_IS_LOCAL ]]; then
+        exec >>"$N7_REMOTE_RUN_DIR/$FUNCNAME" 2>&1
+    else
+        exec >> "$N7_INTERNAL_ERR_FILE" 2>&1
+    fi
 
 # Here we include the remote built-in definitions.
 #
@@ -918,6 +938,29 @@ N7::get_sudo() {
     local sudo=${1:-$N7_SUDO}
     if [ "$sudo" = 1 ]; then echo "$N7_SUDO"; else echo "$sudo"; fi
 }
+
+
+# Show the line and line number of the task the exited with a non-zero status.
+# Use it in a remote task like this: set -e; trap 'N7::remote::tasks::stack_trace $?' ERR
+#
+N7::remote::tasks::stack_trace() {
+    local traceline=$(i=0; while caller $((i++)); do :; done)
+    local topline=$(head -n1 <<<"$traceline")
+    local lineinfo=( $topline ) # ie, (lineNo. func_name /src/file)
+
+    # Use this instead of ${lineinfo[2]} since path may contain spaces.
+    local srcfile=${topline#* }; srcfile=${srcfile#* }  
+
+    local offset=$(( ${lineinfo[0]} - $(grep -m1 -n ^${lineinfo[1]} "$srcfile" | cut -d: -f1) ))
+
+    echo "Exit $1 from line $offset of task ${lineinfo[1]}:"
+    echo "$(sed -n ${lineinfo[0]}p "$srcfile")"
+    echo 
+    echo "Stack trace -------------:"
+    echo "$traceline"
+
+} >&2
+
 
 
 # Functions under the N7::remote "namespace can be used both remotely and locally.
@@ -1008,11 +1051,10 @@ if "failed" in data:
 }
 
 
-    if [[ ! $N7_IS_LOCAL ]]; then
-        exec 1>&3 2>&4
-        exec 3>&- 4>&-
-    fi
-} # >> "$N7_INTERNAL_ERR_FILE" 2>&1
+    eval "exec 1>&$fd1 2>&$fd2"
+    eval "exec $fd1>&- $fd2>&-"
+} 
+
 
 
 #
@@ -1084,13 +1126,23 @@ N7::local::commands::send_funcs() {
     done
     [[ $failed ]] && N7::die "Failed locating functions: ${failed[*]}"
 
-    local f hosts=$(N7::ssh_ehosts)
-    for f in "${funcs[@]}"; do
-        if [[ $N7_REMOTE_STDERR_TO_STDOUT ]]; then
-            f=$(printf %s "$f" | sed '$s/}/} 2>\&1/')
-        fi
-        no_subshell=1 N7::local::commands::remote "$f"
-    done
+    local hosts=$(N7::ssh_ehosts)
+    if [[ $N7_REMOTE_STDERR_TO_STDOUT ]]; then
+        local f i=0 j
+        for f in "${funcs[@]}"; do
+            # skip redirecting command line tasks since they are already, by default, redirected.
+            ((j = i + 1))
+            if [[ ${!j} =~ ^\.N7::cli_task:: ]]; then
+                continue
+            fi
+            funcs[$i]=$(printf %s "$f" | sed '$s/}$/} 2>\&1/')
+            ((++i))
+        done
+    fi
+    local src=$(N7::q "$N7_REMOTE_TASKS_SRC")
+    N7::local::commands::remote "echo '$(printf '%s\n' "${funcs[@]}" | base64)' | base64 --decode >> $src"
+    no_subshell=1 N7::local::commands::remote "source $src"
+
     if [[ $N7_EHOSTS != $hosts ]]; then return $?; fi
 }
 
