Allow a local task to also run without a subshell.

diff --git a/bin/n7 b/bin/n7
--- a/bin/n7
+++ b/bin/n7
@@ -123,7 +123,7 @@ N7_DEFAULT_TASK_TYPE=${N7_DEFAULT_TASK_TYPE:-LOCAL}
 N7_TASK_OPT_NAMES=(
   DESCRIPTION     # describe what the task does.
   TIMEOUT         # timeout in seconds for the remote task.
-  NO_SUBSHELL     # set it to run the remote task directly in the N7 login shell.
+  NO_SUBSHELL     # set it to run the task directly in the N7 login shell.
 
   LOCAL           # set it to run the task locally.
   REMOTE          # set it to run the task remotely.
@@ -170,9 +170,10 @@ mkdir -p "$N7_DIR" "$N7_DIR/tmp" "$N7_RUNS_DIR" "$N7_RUN_DIR"
 # used for temporarily storing updated N7_EHOSTS by a local task.
 N7_EHOSTS_FILE=$N7_RUN_DIR/.ehosts
 
-# where stderr goes during process clean up.
-# mainly used to silence bash's child-process-got-killed message.
-N7_CLEANUP_ERR_FILE=$N7_RUN_DIR/.cleanup.err
+# where stderr goes during N7 init or process clean up.
+# mainly used to silence N7's init task outputs and 
+# bash's child-process-got-killed message during process clean up.
+N7_INTERNAL_ERR_FILE=$N7_RUN_DIR/.cleanup.err
 
 # The command to run sudo. Options can be added too.
 # Eg, N7_SUDO='sudo -u someone'
@@ -228,7 +229,7 @@ trap 'N7::cleanup' ABRT ERR TERM QUIT INT EXIT HUP
 N7::cleanup() {
     # this is to silence bash from reporting to stderr that a
     # child process was killed with SIGKILL.
-    exec 2>>"$N7_CLEANUP_ERR_FILE"
+    exec 2>>"$N7_INTERNAL_ERR_FILE"
     
     N7::close_ssh_pipes
     rm -f "$N7_EHOSTS_FILE"
@@ -244,18 +245,21 @@ N7::ssh_host_from_out_file() { echo $(basename "${1%.out}"); }
 N7::send_cmd() { printf "%s\n" "$1" >"$(N7::ssh_read_pipe ${2:?'Empty host!'})"; }
 
 N7::send_eot_line() {
-    N7::send_cmd "echo $N7_EOT ${1:--} ${N7_TASK_IDX:--1} ${2:-\$?} | tee /dev/stderr" $1
+    local changed_f=$(N7::remote::tasks::change_file)
 
-#    local changed_f=$(N7::task_state_changed) #FIXME
-#    # the line is: <eot_hash> <hostname> <task_index> <exit_status> <changed|->
-#    N7::send_cmd "echo $N7_EOT ${1:--} ${N7_TASK_IDX:--1} ${2:-\$?} \
-#                       \$([ -e $(N7::q "$changed_f") ] && echo changed || echo -) |
-#                  tee /dev/stderr
-#    " $1
+    # the line is: <eot_hash> <hostname> <task_index|-1> <exit_status|$?> <changed|->
+    local line="$N7_EOT $1 ${N7_TASK_IDX:--1} ${2:-\$?} \
+               \$([ -e $(N7::q "$changed_f") ] && echo changed || echo -)"
+
+    N7::send_cmd "echo ; echo $line; echo >&2; echo $line >&2" ${1:?'Empty host!'}
+    #
+    # NOTE: we always output a newline before sending the EOT line so
+    #       that the EOT line will always be on its own line.
 }
 
 
 N7::is_num() { [ "$1" ] && printf "%.0f" "$1" >/dev/null 2>&1; }
+N7::is_int() { [ "$1" ] && printf "%d" "$1" >/dev/null 2>&1; }
 N7::mktemp() {
     tmpdir=$n7_run_dir mktemp -t .tmp.XXXXXXXXXXX ||
         N7::die "Failed creating a temporary file!"
@@ -396,7 +400,7 @@ N7::wait_for_task_on_hosts() {
     SECONDS=0
     while (( SECONDS < timeout )); do
         sleep 0.01
-        eot_lines=$(IFS=$'\n'; tail -v -n1 $out_files | grep -aPB1 "^$N7_EOT [^ ]+ \b$task_idx\b \d+$")
+        eot_lines=$(IFS=$'\n'; tail -v -n1 $out_files | grep -aPB1 "^$N7_EOT [^ ]+ \b$task_idx\b \d+")
         # Note: with tail's '==> path <==' headers.
 
         out_files=$(
@@ -430,15 +434,23 @@ N7::wait_for_task() {
     local show_output=$?
 
     # wait for the EOT marker at the end in each host's out file
-    while read _ host _ rc; do
+    while read _ host _ rc _; do
         if [ "$show_output" = 0 ]; then
             out_file=$(N7::ssh_out_file $host)
-
-            #FIXME: this shoudn't be task_idx - 1 but should be the last remote task's index instead.
             from_line=$(grep -an "^$N7_EOT $host $((task_idx - 1)) " "$out_file" |
                     tail -n1 | cut -d: -f1)
             let ++from_line
             tail -n+$from_line "$out_file" >&2 
+            #
+            #NOTE: when outputing stdout, we are not removing the EOT line nor the
+            #      empty line before it because even though those are not send by
+            #      the user, removing them risk removing user output in the case
+            #      of timeout.
+            #
+            # The N7::local::tasks::get_stdout() won't output the EOT line, and
+            # using $(...) with the function usually gives the desired result
+            # because bash always remove trailing newlines from a command
+            # substitution.
         else
             N7::log "$host rc=$rc" >&2
         fi
@@ -493,7 +505,7 @@ N7::ssh_connect() {
           # to it before the chmod.
           chmod a-w "$ssh_pipe" &&
           while true; do cat "$ssh_pipe" >/dev/null; done #FIXME: don't discard the data read?
-        ) 2>>"$N7_CLEANUP_ERR_FILE" & set +m
+        ) 2>>"$N7_INTERNAL_ERR_FILE" & set +m
         N7_SSH_PPIDs+=($!)
 
         # this is just to keep the pipe from being closed when its
@@ -514,36 +526,35 @@ N7::ssh_connect() {
 # Moreover, the following environment variables will be available to all tasks:
 #
 #   N7_TASK_IDX - The index number(0-based) of the current task.
-#   N7_EHOSTS - "The effective hosts". A space separated list of hosts that the
-#               current task is going through.
+#   N7_EHOSTS   - "The effective hosts". A space separated list of hosts that the
+#                 current task is going through.
+#   N7_HOST     - The host on which the current task is running.
 #
 N7::run_tasks() {
     # the "effective" host list. It gets updated by `run_tasks()' while N7_HOSTS doesn't.
-    local N7_EHOSTS=$(echo $2)
-
     # export it so this will be available to local tasks.
-    export N7_EHOSTS
+    local N7_EHOSTS=$(echo $2); export N7_EHOSTS
+    local N7_TASK_IDX=-1; export N7_TASK_IDX
 
     set -- $1
 
-    local host task
-    local N7_TASK_IDX=-1 rc no_subshell sudo
-    export N7_TASK_IDX
-
-    export N7_TASKS # for local tasks
-
     N7::ssh_connect $N7_EHOSTS
 
+    local host task rc no_subshell sudo
     while [[ $# > 0 && -n "$N7_EHOSTS" ]]; do
         task=$1; shift
         let ++N7_TASK_IDX
+        no_subshell=$(N7::get_task_opt $N7_TASK_IDX NO_SUBSHELL)
 
         N7::log "Running Task #$N7_TASK_IDX: $(N7::get_task_opt $N7_TASK_IDX NAME) ..."
 
-        # handle local task, which has no timeout control, and runs in a subshell.
+        # handle local task, which has no timeout control.
         if [ "$(N7::get_task_opt $N7_TASK_IDX LOCAL)" ]; then
-            export N7_HOST=localhost; ($task) ; rc=$?
+            export N7_HOST=localhost;
+
+            if [ "$no_subshell" ]; then $task; else ($task); fi; rc=$?
             N7::log "localhost rc=$rc"
+
             if [ "$rc" != 0 -a ! "$(N7::get_task_opt $N7_TASK_IDX IGNORE_STATUS)" ]; then
                 N7::die "Error running local task #$N7_TASK_IDX: $(N7::get_task_opt $N7_TASK_IDX NAME)"
             fi
@@ -557,7 +568,6 @@ N7::run_tasks() {
             continue
         fi
 
-        no_subshell=$(N7::get_task_opt $N7_TASK_IDX NO_SUBSHELL)
 
         # send the remote task to each host
         for host in $N7_EHOSTS; do
@@ -927,7 +937,7 @@ eval "$(declare -f N7::local::tasks::get_stdout \
 EOF
     }
     N7::remote::tasks::change_file() {
-        local task_idx = ${1:-$N7_TASK_IDX}
+        local task_idx=${1:-$N7_TASK_IDX}
         if [ "$N7_HOST" != "localhost" ]; then
             echo "$N7_REMOTE_RUN_DIR/task_$task_idx.change"
         else
@@ -973,7 +983,7 @@ N7::load_task_opts ${N7_TASKS[*]}
 
 
 # Run N7 built-in tasks first
-N7::run_tasks_on_hosts "${N7_BUILTIN_TASKS[*]}" "${N7_HOSTS[*]}" >/dev/null 2>&1 #FIXME: write to a file
+N7::run_tasks_on_hosts "${N7_BUILTIN_TASKS[*]}" "${N7_HOSTS[*]}" >>"$N7_INTERNAL_ERR_FILE" 2>&1
 
 # Remove built-in tasks like it never happened
 for i in $(seq 0 $(( ${#N7_BUILTIN_TASKS[*]} - 1)) ); do
